### ISSUE TITLE
$ motuclient -h throws an error in version 1.8.5

### ISSUE THREAD

**Issue by jimc101** [clstoulouse/motu-client-python#23]
When I try to invoke help using version 1.8.5 I receive the error:

[ERROR] Execution failed: %d format: a number is required, not dict

Steps to reproduce:

$ conda create -n motuclient python==3.6
$ pip install motuclient
$ motuclient -h
<time_stamp> [ERROR] Execution failed: %d format: a number is required, not dict

The same failure occurs when I try later versions of python (3.8). When running:

$ pip install motuclient==1.8.4

the help message appears as expected.

**Comment by clstoulouse** [comment]
Hi,

Yes there is an issue that we have reproduced so we are going to fix it during the next weeks. We will keep you in touch as soon as the new version fixing it will be available.

Thanks for sharing this issue.

Regards,
CLS Motu teams

**Comment by clstoulouse** [comment]
While waiting for the fix, here is the help:

`usage: motuclient.py [-h] [--version] [--quiet] [--verbose] [--noisy]
                     [--user USER] [--pwd PWD] [--auth-mode AUTH_MODE]
                     [--proxy-server PROXY_SERVER] [--proxy-user PROXY_USER]
                     [--proxy-pwd PROXY_PWD] [--motu MOTU]
                     [--service-id SERVICE_ID] [--product-id PRODUCT_ID]
                     [--date-min DATE_MIN] [--date-max DATE_MAX]
                     [--latitude-min LATITUDE_MIN]
                     [--latitude-max LATITUDE_MAX]
                     [--longitude-min LONGITUDE_MIN]
                     [--longitude-max LONGITUDE_MAX] [--depth-min DEPTH_MIN]
                     [--depth-max DEPTH_MAX]
                     [--variable VARIABLE [VARIABLE ...]] [--sync-mode]
                     [--describe-product] [--size] [--out-dir OUT_DIR]
                     [--out-name OUT_NAME] [--block-size BLOCK_SIZE]
                     [--socket-timeout SOCKET_TIMEOUT]
                     [--user-agent USER_AGENT] [--outputWritten OUTPUTWRITTEN]
                     [--console-mode] [--config-file CONFIG_FILE]

 

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --quiet, -q           prevent any output in stdout
  --verbose             print information in stdout
  --noisy               print more information (traces) in stdout
  --user USER, -u USER  the user name (string)
  --pwd PWD, -p PWD     the user password (string)
  --auth-mode AUTH_MODE
                        the authentication mode: 'none' (for no
                        authentication), 'basic' (for basic authentication),
                        or 'cas' (for Central Authentication Service)
                        [default: cas]
  --proxy-server PROXY_SERVER
                        the proxy server (url)
  --proxy-user PROXY_USER
                        the proxy user (string)
  --proxy-pwd PROXY_PWD
                        the proxy password (string)
  --motu MOTU, -m MOTU  the motu server to use (url)
  --service-id SERVICE_ID, -s SERVICE_ID
                        The service identifier (string)
  --product-id PRODUCT_ID, -d PRODUCT_ID
                        The product (data set) to download (string)
  --date-min DATE_MIN, -t DATE_MIN
                        The min date with optional hour resolution (string
                        following format YYYY-MM-DD [HH:MM:SS])
  --date-max DATE_MAX, -T DATE_MAX
                        The max date with optional hour resolution (string
                        following format YYYY-MM-DD [HH:MM:SS])
  --latitude-min LATITUDE_MIN, -y LATITUDE_MIN
                        The min latitude (float in the interval [-90 ; 90])
  --latitude-max LATITUDE_MAX, -Y LATITUDE_MAX
                        The max latitude (float in the interval [-90 ; 90])
  --longitude-min LONGITUDE_MIN, -x LONGITUDE_MIN
                        The min longitude (float)
  --longitude-max LONGITUDE_MAX, -X LONGITUDE_MAX
                        The max longitude (float)
  --depth-min DEPTH_MIN, -z DEPTH_MIN
                        The min depth (float in the interval [0 ; 2e31] or
                        string 'Surface')
  --depth-max DEPTH_MAX, -Z DEPTH_MAX
                        The max depth (float in the interval [0 ; 2e31] or
                        string 'Surface')
  --variable VARIABLE [VARIABLE ...], -v VARIABLE [VARIABLE ...]
                        The variable (list of strings)
  --sync-mode, -S       Sets the download mode to synchronous (not
                        recommended)
  --describe-product, -D
                        Get all updated information on a dataset. Output is in
                        XML format
  --size                Get the size of an extraction. Output is in XML format
  --out-dir OUT_DIR, -o OUT_DIR
                        The output dir where result (download file) is written
                        (string). If it starts with 'console', behaviour is
                        the same as with --console-mode.
  --out-name OUT_NAME, -f OUT_NAME
                        The output file name (string)
  --block-size BLOCK_SIZE
                        The block used to download file (integer expressing
                        bytes)
  --socket-timeout SOCKET_TIMEOUT
                        Set a timeout on blocking socket operations (float
                        expressing seconds)
  --user-agent USER_AGENT
                        Set the identification string (user-agent) for HTTP
                        requests. By default this value is 'Python-urllib/x.x'
                        (where x.x is the version of the python interpreter)
  --outputWritten OUTPUTWRITTEN
                        Optional parameter used to set the format of the file
                        returned by the download request, only netcdf is
                        supported. If not set, netcdf is used.
  --console-mode        Optional parameter used to display result on stdout,
                        either URL path to download extraction file, or the
                        XML content of getSize or describeProduct requests.
  --config-file CONFIG_FILE
                        Path of the optional configuration file [default:
                        ~/motuclient/motuclient-python.ini]
`

**Comment by clstoulouse** [comment]
Fixed within release 1.8.6
