### ISSUE TITLE
Passwords need to be manually url-encoded

### ISSUE THREAD

**Issue by logi** [clstoulouse/motu-client-python#25]
I have a MOTU password with one or more characters which are not URL safe. Between versions 1.8.4 and 1.8.7 authentication stopped working. The error message helpfully warns about properly quoting the credentials, but I had to read through recent commits to find out that passwords (and usernames) are no longer url-encoded automatically and that I would need to manually encode the password for it to work. Which it then did.

This is presumably an accidental byproduct of this change which should be reverted.
https://github.com/clstoulouse/motu-client-python/commit/f37b9b6ad4be23e70d6b35b83e25b87bd9ce94d1#diff-00b94775030dffb048df59ed6ae7cbca08892c53ccc747e120e6de484a41b8dcL91

**Comment by clstoulouse** [comment]
Dear @logi ,
Just to investigate more deeply your issue, could you please confirm if you have a password which includes either a space ' ' character or a hastag '#' character ?

Regards

**Comment by logi** [comment]
Hello @clstoulouse.

The password contains a question-mark `?` character and I had to replace it with `%26` after consulting an ASCII table.

**Comment by clstoulouse** [comment]
Thank you for your quick reply, we are going to investigate this issue and come back to you soon.

**Comment by logi** [comment]
A further problem is that you can't put `%26` in the `pwd` field in the ini file since it is being interpreted as a variable interpolation token at some level.

With `%26` in the code it exits with:
```
[ERROR] Execution failed: '%' must be followed by '%' or '(', found: '%26"'
```

Replacing that with `%(26)` results in this failure:
```
[ERROR] Execution failed: bad interpolation variable reference '%(26)"'
```

However, using `%%26` works. Pesumably `%%` is taken as a literal `%` by the interpolation code and `%26` is passed through to be interpreted as `&` by the access-control service.

**Comment by clstoulouse** [comment]
Hi @logi ,

Just to inform that new release fixes your issue. Please try it https://github.com/clstoulouse/motu-client-python/releases/tag/motuclient-python-1.8.8 !

Download link: https://github.com/clstoulouse/motu-client-python/releases/download/motuclient-python-1.8.8/motuclient-python-1.8.8-20210219115938030-bin.tar.gz

Regards,
CLS Motu Team

**Comment by logi** [comment]
Can confirm that 1.8.8 solves my issue. Thanks for the fix!

**Comment by clstoulouse** [comment]
Great, thanks for your feedback !
