### ISSUE TITLE
Error install motu-client-python

### ISSUE THREAD

**Issue by ZenKa24** [clstoulouse/motu-client-python#3]
I got errors below when I run this command:
**mvn clean install -Dmaven.test.skip=true**
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project cls.atoll.motu.client:motu-client-python:1.4.00 (/home/ubuntu/motu-client-python/po
m.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find cls.commons:cls-project-config:pom:1.2.00 in http:
//repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted unt
il the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at w
rong local POM @ line 2, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Please check it to me!

Thank you so much!

**Comment by clstoulouse** [comment]
Dear,

To fix it, edit motu-client-python/pom.xml file and comment lines below (line 2 to 6):
```
    <!-- <parent>
		<artifactId>cls-project-config</artifactId>
		<groupId>cls.commons</groupId>
		<version>1.2.00</version>
	</parent> -->
```

This "maven" command is used to build the tar.gz file from sources. We have already built this archive for you and you can download it diretly from [https://github.com/clstoulouse/motu-client-python/releases](https://github.com/clstoulouse/motu-client-python/releases) ([motu-client-python-1.4.00-20170410143941999-bin.tar.gz](https://github.com/clstoulouse/motu-client-python/releases/download/motu-client-python-1.4.00/motu-client-python-1.4.00-20170410143941999-bin.tar.gz) for the current last version).
then install the archive: [https://github.com/clstoulouse/motu-client-python#installation](https://github.com/clstoulouse/motu-client-python#installation)

If you want to build the project, install MAVEN [https://maven.apache.org/install.html](https://maven.apache.org/install.html)
and then follow: [https://github.com/clstoulouse/motu-client-python#Build](https://github.com/clstoulouse/motu-client-python#Build)

In the next version, we will add the project on Python Pypi repository to ease installation in a full python environment.

Best Regards.

**Comment by ZenKa24** [comment]
It worked fine.
Thank you so much!
