### ISSUE TITLE
Motu-client upgrade to Python 3

### ISSUE THREAD

**Issue by rgallou** [clstoulouse/motu-client-python#4]
Hi All,

We're wondering if there is an plan for upgrade Motu-client to be supported by Python 3 ?
Thanks in advance.

Best regards.

**Comment by clstoulouse** [comment]
Hi,

This is off course an upgrade which is really interesting and useful, but for the next coming months it is not planned.

If you are interested by developing it, you can submit a merge request and we will take time to integrate this upgrade.

Best regards.

**Comment by kmarshfgg** [comment]
Hi,

I have re-factored the Python 2 code and I am now able to successfully download data via the motu client in Python 3.4.

I'm new to GitHub so please let me know the best way to share my code.

**Comment by clstoulouse** [comment]
Hi,

Thanks a lot for your work. The easier way is to send us a GitHub pull request (https://help.github.com/articles/about-pull-requests/). 

Then we will review your source code updates, validate the code to be sure that it runs with both last python 2.x and 3.x and when all runs successfully, we will integrate it in develop branch and release a new version.

Best regards.

**Comment by clstoulouse** [comment]
Hi,

The new version [1.7.0 ](https://github.com/clstoulouse/motu-client-python/releases/tag/motu-client-python-1.7.00) is now fully compatible with Python 3.

Enjoy Motu!
Sylvain
