### ISSUE TITLE
Quiet switch non fully working on v 1.5.0

### ISSUE THREAD

**Issue by fmarzocca** [clstoulouse/motu-client-python#5]
In v.1.5.0, when launching this command line:

`$HOME/motu-client/motu-client.py -s MEDSEA_ANALYSIS_FORECAST_WAV_006_011-TDS  -x -10 -X 36.5 -y 30 -Y 46 -t "2018-04-07" -T "2019-04-07" -v VHM0 -v VMDR -v VTM10 -q -o console`

the output is not reporting only the resulting url but it also adds 3 lines of:

`dname=<my motu-client home>`

**Comment by fmarzocca** [comment]
I applied the patch and now it is working fine!
Thanks

**Comment by clstoulouse** [comment]
Great! Thanks for your feedback!
