### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by jblarsen** [clstoulouse/motu-client-python#7]
System:
`$ uname -a
Linux orca 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I get this error:
`$ pip2 install motu-client --user

Collecting motu-client
  Downloading https://files.pythonhosted.org/packages/8d/0b/c78868dac2507dc9ebe2c622508f2a64e96fb74cec1278066f3f1f4f25a2/motu-client-1.6.00.zip (40kB)
    100% |████████████████████████████████| 40kB 820kB/s 
Building wheels for collected packages: motu-client
  Running setup.py bdist_wheel for motu-client ... done
  Stored in directory: /home/jbl/.cache/pip/wheels/bf/9c/a3/9fba3e1d10eac8854603513d8f7a1d1807ade7261c958bf97d
Successfully built motu-client
Installing collected packages: motu-client
motu-client is in an unsupported or invalid wheel
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

I have tried to delete .cache/pip before installing.

**Comment by ElusiveTau** [comment]
The error message reports you're using pip 8.1.1. Did you try upgrading pip to 10.0.1? 

If that doesn't work, try cloning the repo and provide the absolute path to the motu-client module `motu-client-python/src/python/motu-client.py` in the shell download string.

**Comment by jblarsen** [comment]
Using a newer pip solved the problem. Thanks for the help.
