### ISSUE TITLE
Invalid date range

### ISSUE THREAD

**Issue by camrinbraun** [clstoulouse/motu-client-python#8]
Anyone know why this works:

`python ~/motu-client.py --user <USER> --pwd <PWD> --motu http://my.cmems-du.eu/motu-web/Motu --service-id GLOBAL_REANALYSIS_BIO_001_018-TDS --product-id dataset-global-nahindcast-bio-001-018-V5-o2 --longitude-min -94 --longitude-max -4 --latitude-min -10 --latitude-max 49 --date-min "2015-12-16 12:00:00" --date-max "2015-12-16 12:00:00" --depth-min 0.5056 --depth-max 508.64 --variable O2 --variable nav_lon --variable nav_lat --out-dir <OUT> --out-name motu-o2.nc`

and this does not:

`python ~/motu-client.py --user <USER> --pwd <PWD> --motu http://my.cmems-du.eu/motu-web/Motu --service-id GLOBAL_REANALYSIS_BIO_001_018-TDS --product-id dataset-global-nahindcast-bio-001-018-V5-o2 --longitude-min -94 --longitude-max -4 --latitude-min -10 --latitude-max 49 --date-min "2015-12-21 12:00:00" --date-max "2015-12-21 12:00:00" --depth-min 0.5056 --depth-max 508.64 --variable O2 --variable nav_lon --variable nav_lat --out-dir <OUT> --out-name motu-o2.nc`

The only thing I change between the two calls is the day of the month (from 2015-12-16 to 2015-12-21). The error is invalid date range. It states:

**[ERROR] 004-6 : The date range is invalid. Invalid date range: [2015-12-21 12:00:00,2015-12-21 12:00:00]. Valid range is: [1998-01-16 12:00:00,2016-12-16 12:00:00].**

**Comment by clstoulouse** [comment]
No data is available for date 2015-12-21, you can check it by running a describeproduct request in your web browser:

http://my.cmems-du.eu/motu-web/Motu?action=describeproduct&service=GLOBAL_REANALYSIS_BIO_001_018-TDS&product=dataset-global-nahindcast-bio-001-018-V5-o2
--- returns:
```
<availableTimes msg="OK" code="0">
...
2015-04-16T00:00:00Z/2015-07-16T12:00:00Z/P1MT12H,
2015-08-16T12:00:00Z/2015-12-16T12:00:00Z/P1MT12H,
2016-01-...
...
```

and this indicates that the last avaiable date for year 2015 is 2015-12-16T12:00:00Z

**Comment by camrinbraun** [comment]
Does the return from your example also indicate that data is missing from 2015-07-17 to 2015-08-15? It seems like many days are missing from this dataset. Thank you.

**Comment by clstoulouse** [comment]
Yes, you're right, data is also missing from 2015-07-17 to 2015-08-15.
